### ISSUE TITLE
很抱歉打扰了

### ISSUE THREAD

**Issue by lueasy559** [PriateXYF/Q-note#1]
羊了个羊无限道具非常给力，但是没两天就不能玩了
您还打算更新吗？
如果不打算更新的话，您可以告诉我如何获取源码吗，我打算自己试一试
等待是焦急的，希望您不会介意
再次致歉，叨饶了！

**Comment by PriateXYF** [comment]
> 羊了个羊无限道具非常给力，但是没两天就不能玩了 您还打算更新吗？ 如果不打算更新的话，您可以告诉我如何获取源码吗，我打算自己试一试 等待是焦急的，希望您不会介意 再次致歉，叨饶了！

我是 fork https://github.com/george-jiang-wow/yanglegeyang 后修改的，并没有拿到源码，目前应该都失效了，如果原作者或者其他人没有修复的话我也不会更新了。另外请不要这个 repo 下提不相关的 issue 。
